### ISSUE TITLE
Can't Connect

### ISSUE THREAD

**Issue by MessingaSquare** [XK9274/syncthing-app-miyoo#11]
I transferred the files using Filezilla via FTP but syncthing on Miyoo is refusing the connection. Could it be that I didn't use binary mode to transfer and that's causing the issue? Thanks.

**Comment by XK9274** [comment]
That could be the problem yes. 

Have you tried copying the files to the SD card directly or using HTTP server, samba or SFTP instead of FTP?

**Comment by XK9274** [comment]
Stale, no reply.
