### ISSUE TITLE
SyncThing doesn't run automatically on 4.3.0 beta

### ISSUE THREAD

**Issue by Levistras** [XK9274/syncthing-app-miyoo#14]
After upgrading to 4.3.0-8ae761fc, SyncThing no longer runs on boot up.  I have to launch it from the Apps menu every time for it to start up.

**Comment by XK9274** [comment]
This will be because the runtime.sh has changed. Did you get this fixed? If not we can look into it together.

**Comment by Levistras** [comment]
I did not get it fixed, I've just been running it manually when I need a sync in the meantime.

I can upload a copy of something off the device if needed.

**Comment by XK9274** [comment]
Sure, can you try:

- Save the /mnt/SDCARD/App/Syncthing/config dir to your PC
- Delete the Syncthing dir
- Open /mnt/SDCARD/.tmp_update/runtime.sh, find the line `sh /mnt/SDCARD/App/Syncthing/script/checkrun.sh #SYNCTHING INJECTOR #SYNCTHING INJECTOR` and remove it
- Add the app back to your device (the Syncthing dir)
- Copy the `config` dir back to /mnt/SDCARD/App/Syncthing
- Re-run the app

**Comment by Levistras** [comment]
I don't see "sh /mnt/SDCARD/App/Syncthing/script/checkrun.sh #SYNCTHING INJECTOR #SYNCTHING INJECTOR" anywhere in runtime.sh.

Did a search for "Syncthing" and it's not there at all.  

I wonder if there's a larger issue here where the Syncthing app can't modify the runtime.sh ?

**Comment by XK9274** [comment]
In an older version of the syncthing there was a file called goTime in the syncthing App dir. Delete this and re-run the app. 

Or, download the new version from the main page here and overwrite the one in your app dir, then re-run the app. 

If it's been a while since you first installed the app then things have probably changed.

There's no issues with the package (tested it the other night).

I'll repackage and do a proper release at some point but, the above are your options

**Comment by Levistras** [comment]
Odd indeed.  I'm running a version downloaded Jan 11th 2024, the files inside have a timestamp of Oct 18th 2023, there's no goTime file.

I manually added the line you referenced into the runtime.sh right before the "# Auto launch" line, and after reboot SyncThing seems to be opening without issue.

Let me try blowing it away completely as you originally suggested.

**Comment by XK9274** [comment]
Sure np, if you have issues let me know & we'll work through it. 👍

**Comment by Levistras** [comment]
After full removal and reinstall, it injected the line just fine into runtime.sh.  Tested after reboot and it's launching just fine by itself.
No idea what was happening there..  I think at one point I installed the new version on-top of the older version, maybe that retained some files that weren't needed and broke it.  
Thanks for the help, closing issue.

**Comment by XK9274** [comment]
Great to hear! Thanks for updating.

Onion now has a startup script function so at some point I'll move it into there.

Cheers!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
