### ISSUE TITLE
Issue with launch on boot 

### ISSUE THREAD

**Issue by HenryAvery** [XK9274/syncthing-app-miyoo#3]
I'm not sure if this has been tested or supports the new 4.2.0 RC. I had no issues installing the app running it and getting the sync to work.

 However, it seems I have to launch the app every time to get it started as it does not launch on startup of the device. I checked the runtime.sh file in the .tmp_update folder and found the line `sh $appdir/script/checkrun.sh #SYNCTHING INJECTOR` just to make sure it got added. Don't know what else to check. 

Thanks for making this cool tool though.

**Comment by XK9274** [comment]
Hey! Yeah this was actually caused by a change i made a little while ago:

I've fixed the repo, but open your runtime.sh and replace:

`sh $appdir/script/checkrun.sh #SYNCTHING INJECTOR`

with

`sh /mnt/SDCARD/App/Syncthing/script/checkrun.sh #SYNCTHING INJECTOR`

**Comment by HenryAvery** [comment]
That fixed it. Thanks a lot. Really enjoying the ability to sync on the MM+.
