### ISSUE TITLE
Broken with Onion OS Update

### ISSUE THREAD

**Issue by MichaelRPowell** [XK9274/syncthing-app-miyoo#4]
Hello,

I have run into another issue. I updated Onion OS and now Syncthing is not working. I read #3 .  I have downloaded the new changes and uploaded the files again.

I will say I did not see any reference to checkrun.sh in ~/.tmp_update/runtime.sh file. I am not sure if the update modifies/wipes the runtime.sh script, but it was odd it was not there.

I manually added the line to be safe:

`sh /mnt/SDCARD/App/Syncthing/script/checkrun.sh #SYNCTHING INJECTOR`

That did not get Syncthing running. I then tried to manually run the command to start Syncthing:

`/mnt/SDCARD/App/Syncthing/bin/syncthing serve --home=/mnt/SDCARD/App/Syncthing/config/ > /mnt/SDCARD/App/Syncthing/serve.log 2>&1 &`

That also did not work. In the serve.log I only have a single error line:

`/mnt/SDCARD/App/Syncthing # vi serve.log`

`/mnt/SDCARD/App/Syncthing/bin/syncthing: line 1: syntax error: unexpected "("`

I am happy to test and help resolve this issue. Just let me know what I can do to assist.

**Comment by XK9274** [comment]
Hello again!

You usually get that error when the file is broken.

Can you do a stat of the syncthing bin?

**Comment by MichaelRPowell** [comment]
I downloaded and uploaded the syncthing file again. I then ran `stat syncthing`:

```
/mnt/SDCARD/App/Syncthing/bin # stat syncthing
  File: syncthing
  Size: 2958516         Blocks: 5824       IO Block: 32768  regular file
Device: b301h/45825d    Inode: 686         Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-07-23 17:26:36.000000000
Modify: 2023-07-23 17:24:24.000000000
```

**Comment by MichaelRPowell** [comment]
Just a note. The SD card does not appear corrupt or having any other issues. I uploaded a new ISO based game yesterday, and it ran fine. I am also gaming on it regularly, and saves are working as expected (not loss or corruption so far).

**Comment by MichaelRPowell** [comment]
Alright, there is something else going on. I was uploading through Filezilla using the FTP option. When I enabled Samba share, I found in the folder there were two files.

syncthing and syncthing.old. Syncthing was about 2 megabytes and syncthing.old was over 22 megabytes. When I uploaded using Filezilla, I told it to overwrite the syncthing file with the new syncthing. I am not sure why that did not work as expected the last two times. I had a similar issue with a previous game, where it seemed like the entire file didn't transfer, but Filezilla reported it had. I might stick to Samba for now until I figure out why Filezilla is having transfer issues.

I am going to close this issue, as syncthing is now working correctly for me.

**Comment by XK9274** [comment]
Hey no worries man, sorry this is a common problem with Filezilla, i added a section in the Onion wiki as it was becoming that much of a problem from transferring binaries, see the fix at the bottom of: https://github.com/OnionUI/Onion/wiki/FTP

**Comment by MichaelRPowell** [comment]
> i added a section in the Onion wiki as it was becoming that much of a problem from transferring binaries, see the fix at the bottom


Thank you for that! I will give that a try next time!
