### ISSUE TITLE
MiyooMini overwrites saves on PC always

### ISSUE THREAD

**Issue by ioslife** [XK9274/syncthing-app-miyoo#5]
I am working to get Syncthing setup for a PC <> NAS <> MiyooMini+ sync. 

Each of these three devices has Syncthing installed and sharing folders for Roms and Saves. When I make a new save on the MiyooMini, the save file will sync properly and it loads on my PC perfectly fine.

When I save again on the PC, I would expect the save to update on the MiyooMini, but instead the MiyooMini is overwriting the PC.

Am I missing something simple here?

**Comment by samiralam** [comment]
I have a similar setup and I can't reproduce this issue.

- Is your syncthing folder configured as "send and receive" on both devices?
- Did you check "ignore permissions" on the advanced tab?

**Comment by XK9274** [comment]
Is this still a problem or does the above resolve?

**Comment by XK9274** [comment]
Stale, no reply.
