### ISSUE TITLE
After updating to 4.2.0 final, Syncthing Web UI no longer working

### ISSUE THREAD

**Issue by Levistras** [XK9274/syncthing-app-miyoo#8]
After updating to 4.2.0 final, Syncthing doesn't reliably run on it's own, I have to manually start it via Terminal/SSH.  

I tried re-running the install script but doesn't seem to change anything.

The WebUI no longer works:
This site can’t be reached
192.168.0.215 refused to connect.
Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED

And (not sure if this was an existing issue), the serve.log file complains repeatedly about a missing x509 certificate:
[GQZ4P] 2023/10/18 03:04:11 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[GQZ4P] 2023/10/18 03:04:11 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) shutting down
[GQZ4P] 2023/10/18 03:04:11 INFO: listenerSupervisor@dynamic+https://relays.syncthing.net/endpoint: service dynamic+https://relays.syncthing.net/endpoint failed: Get "https://relays.syncthing.net/endpoint": tls: failed to verify certificate: x509: certificate signed by unknown authority

**Comment by Levistras** [comment]
Also seeing some read-only file system errors in the logs:

[GQZ4P] 2023/10/18 03:02:56 WARNING: Saving .stignore: open /mnt/SDCARD/Saves/CurrentProfile/.syncthing.tmp.461435488: read-only file system
[GQZ4P] 2023/10/18 03:02:57 WARNING: Saving config: open /mnt/SDCARD/App/Syncthing/config/.syncthing.tmp.126558271: read-only file system
[GQZ4P] 2023/10/18 03:03:09 WARNING: Saving .stignore: open /mnt/SDCARD/Saves/CurrentProfile/.syncthing.tmp.907041426: read-only file system
[GQZ4P] 2023/10/18 03:03:09 WARNING: Saving config: open /mnt/SDCARD/App/Syncthing/config/.syncthing.tmp.678357705: read-only file system

**Comment by Levistras** [comment]
Ignore this... had to delete the gotime file and now she's working.

**Comment by XK9274** [comment]
Thanks, the read only file system error is concerning. It's usually when the SD mount has become damaged or left dangling. 

Glad it's sorted but if there's any other issues let me know.. I need to make sure the injector still works and sits in the correct place anyway.

**Comment by samiralam** [comment]
FWIW, I tested it last night with a clean install of 4.2 (final) and it seemed to inject properly.

**Comment by Levistras** [comment]
Maybe the install script could be modified to check to see if a full install is required somehow so manual deletion of the gotime file isn't necessary?   It is working fine now as far as I can tell.
